config/routes.rb
Rails.application.routes.draw do
  
  get 'books/index'

  get 'books/show'

  get 'books/new'

  get 'books/edit'

  root      'static_pages#home'
  get       '/about',       to: 'static_pages#about'
  get       '/return',      to: 'static_pages#return'
  get       '/signup',      to: 'users#new'
  get       '/login',       to: 'sessions#new'
  post      '/login',       to: 'sessions#create'
  delete    '/logout',      to: 'sessions#destroy'
  delete    '/return',      to: 'borrowings#return'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :books
  resources :borrowings,          only: [:index, :create, :update, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :admin_user, only: [:return]

  def home
    if @user = current_user
      unless @user.admin?
        @borrowings = @user.borrowings.where("verified LIKE ?", true)
        @books = Array.new
        @borrowings.each { |b| @books << Book.find_by(id: b.book_id) }
      else
        @borrowings = Borrowing.where.not(request: nil)
      end
    end
  end

  def about
  end

  def return
    if params[:search_user_id] 
      if @user = User.find_by(id: params[:search_user_id])
        @borrowings = @user.borrowings
      else
        flash[:warning] = "Not found user"
      end
    end
    store_location
  end

  private 
     def admin_user
        unless current_user_admin? 
          flash[:danger] = "You're not admin user!"
          redirect_to root_url
        end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_librian.html.erb
<h3>All books are being borrowed</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>User</th>
      <th>Due date</th>
      <th>Request</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% get_borrowings.each do |e| %>
      <tr>
        <th><%= Book.find_by(id: e.book_id).title %></th>
        <th><%= Book.find_by(id: e.book_id).author %></th>
        <th><%= User.find_by(id: e.user_id).name %></th>
        <th><%= e.due_time %></th>
        <th><%=  %></th>
        <th>
          <%= form_for e, method: :patch do |f| %>
            <%= hidden_field_tag :verify, true %>
            <%= hidden_field_tag :user_id, e.user_id %>
            <%= hidden_field_tag :book_id, e.book_id %>
            <%= f.submit "Approve", class: 'btn btn-primary' %>
          <% end %>
        </th>
        <th>
          <%= form_for e, method: :delete do |f| %>
            <%= hidden_field_tag :deny_verify, true %>
            <%= hidden_field_tag :user_id, e.user_id %>
            <%= hidden_field_tag :book_id, e.book_id %>
            <%= f.submit "Deny", class: 'btn btn-warning' %>
          <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>    

app/views/static_pages/_table_librarian.html.erb
<h3>All books are being borrowed</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>User</th>
      <th>Due date</th>
      <th>Request</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% get_borrowings.each do |e| %>
      <tr>
        <td><%= Book.find_by(id: e.book_id).title %></td>
        <td><%= Book.find_by(id: e.book_id).author %></td>
        <td><%= User.find_by(id: e.user_id).name %></td>
        <td><%= e.due_time %></td>
        <td><%= e.request %></td>
        <%= render 'shared/approve', object: e %>
        <%= render 'shared/deny',    object: e%>
      </tr>
    <% end %>
  </tbody>
</table>    

app/views/static_pages/_table_user.html.erb
<h3>All books are being borrowed</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Due date</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr class="<%= 'danger' if book.has_expired?(current_user) %>">
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= book.get_due_time(current_user) %></td>
        <% if book.has_expired?(current_user) %>
          <td>
            <% if !book.get_borrowing(current_user).request.nil? %>
              Waiting approving from librarian
            <% else %>
              <%= render 'shared/extend', object: book.get_borrowing(current_user) %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Capstone home") %>
<% if logged_in? %>
    <% if current_user_admin? %>
      <%= render 'table_librarian' %>
    <% else %>
      <%= render 'table_user' %>
    <% end %>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Capstone Library</h1>

    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Capstone Library</a>
      application.
    </h2>
    <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
  </div>
<% end %>     

app/views/static_pages/return.html.erb
<h2 class="text-center">Return book</h3>

<%= form_tag return_path, method: :get, class: 'form-inline' do %>
  <div class="form-group">
    <label>Enter user id: </label>
    <div class="input-group">
      <input name="search_user_id" id="search_user_id" class="form-control" type="number">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
<% end %>

<% unless @user.nil? %>
    <% if @borrowings.count == 0 %>
        <h4><%= @user.name %> doesn't borrow any books</h4>
    <% else %>
        <%= render 'shared/table_return', object: @borrowings %>
    <% end %>
<% end %>