config/routes.rb
Rails.application.routes.draw do
  
  get 'books/index'

  get 'books/show'

  get 'books/new'

  get 'books/edit'

  root      'static_pages#home'
  get       '/about',       to: 'static_pages#about'
  get       '/return',      to: 'static_pages#return'
  get       '/signup',      to: 'users#new'
  get       '/login',       to: 'sessions#new'
  post      '/login',       to: 'sessions#create'
  delete    '/logout',      to: 'sessions#destroy'
  delete    '/return',      to: 'borrowings#return'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :books
  resources :borrowings,          only: [:index, :create, :update, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Capstone app 
    by <a href="https://www.facebook.com/binhthuan274">Minh Thuan</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "capstone library", root_path, id: "logo" %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_tag books_path, method: 'get' do %>
            <%= text_field_tag :search, params[:search], class: 'form-control', type: 'search' %>
          <% end %>
        </li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Books", books_path %></li>
        <% if current_user_admin? %>
          <li><%= link_to "Return", return_path %></li> 
        <% end %>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>